version: "3.9"
services:
  node:
    build: .
    image: tb/rest-app
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    command: sh -c './wait-for postgres:5432 -t 600 -- npm run start:dev'
    volumes:
      - ./src:/usr/src/app/src
    environment:
      PORT: ${PORT}
    restart: on-failure
    networks:
      - net
  postgres:
    build: ./database
    image: tb/rest-app-postgres
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - ./db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - net
networks:
  net:
    driver: bridge
