version: '3'
services:
  app:
    container_name: app
    build: .
    image: tb/rest
    volumes:
      - ./src:/usr/app/src
    network_mode: my-net
    restart: on-failure
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    environment:
      PORT: ${PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
    networks:
      - my-network
  db:
    container_name: postgres
    build: ./docker/db/
    image: tb/postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - my-network

networks:
  my-network:
    driver: bridge